// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarContainer: typeof import('./layouts/components/AvatarContainer.vue')['default']
    Container: typeof import('./components/Container/Container.vue')['default']
    ContainerInner: typeof import('./components/Container/ContainerInner.vue')['default']
    ContainerOuter: typeof import('./components/Container/ContainerOuter.vue')['default']
    DesktopNavigation: typeof import('./layouts/components/DesktopNavigation.vue')['default']
    Footer: typeof import('./layouts/components/Footer.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Header: typeof import('./layouts/components/Header.vue')['default']
    IHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    MobileNavigation: typeof import('./layouts/components/MobileNavigation.vue')['default']
    MobileNavItem: typeof import('./layouts/components/MobileNavItem.vue')['default']
    NavItem: typeof import('./layouts/components/NavItem.vue')['default']
    NavLink: typeof import('./layouts/components/NavLink.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverOverlay: typeof import('@headlessui/vue')['PopoverOverlay']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/elements/Section.vue')['default']
    SimpleLayout: typeof import('./components/SimpleLayout.vue')['default']
    Tool: typeof import('./components/index/Tool.vue')['default']
    ToolsSection: typeof import('./components/index/ToolsSection.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
